#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Script to prepend the Multiplex ID before the Channelname. 
#You can view and record multiple Channels if they are on the same Multiplexer.

id=0
SQL_1='SELECT `callsign`, `mplexid`, `chanid` FROM `channel`;'
mysql -u mythtv -pmythtv mythconverg -h joed.homeip.net -e "$SQL_1" | while read line
do
  name=$(echo "$line"    |cut -f1 )
  mplexid=$(echo "$line" |cut -f2 )
  chanid=$(echo "$line"  |cut -f3 )
  echo "$chanid $mplexid $name"
  SQL_2='UPDATE  `mythconverg`.`channel` SET  `callsign` =  "'$mplexid"_"$name'" WHERE  `channel`.`chanid` ='$chanid' LIMIT 1 ;'
  #echo $SQL_2
  mysql -u mythtv -pmythtv mythconverg -h joed.homeip.net -e "$SQL_2"
done
 
