#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Script to check all files for Passwords before commiting

PW=`cat /etc/cardatgirls`
for p in $PW
do
  OP=$OP" -e $p "
done
/bin/grep $OP *
if [ $? == 0 ] ;
then	    # Aktion wenn bereits gemountet;
  echo "!!!!!!!WARNUNG!!!!!!!"
  echo "  PASSWORT GEFUNDEN  "
  echo "!!!!!!!WARNUNG!!!!!!!"
  exit 1;
else      # Aktion wenn noch nicht gemountet;
  echo "GOOD! No Password found!"
fi
