#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Cleans out any Profile Data and starts Chromium in a clean enviroment.

#rm -rf /home/joe/.config/chromium/Clean 
chromium-live --user-data-dir=/tmp/chromium/Clean -enable-default-apps
