#!/bin/zsh
#get_photos
MOBILE_MP="/mnt/c905/Memory_Stick"
mount | grep $MOBILE_MP ; # <-- z.B. /home
if [ $? == 0 ] ;
  then	    # Aktion wenn bereits gemountet;
    echo "Already mounted - Good!"
  else      # Aktion wenn noch nicht gemountet;
    echo "Not mounted. Mounting now: "
    sudo mount $MOBILE_MP
    echo "Status of mount: $?"
fi

mv "$MOBILE_MP/DCIM/100MSDCF/"* "/home/joe/_Handy/_Incomming"
#rsync -r $MOBILE_MP/DCIM/100MSDCF/ /home/joe/_Handy/_Incomming --del --progress