#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Mounting my mobile and moving the Photos from the Camera to the PC

MOBILE_MP="/mnt/defy"
mount | grep $MOBILE_MP ; # <-- z.B. /home
if [ $? == 0 ] ;
  then	    # Aktion wenn bereits gemountet;
    echo "Already mounted - Good!"
  else      # Aktion wenn noch nicht gemountet;
    echo "Not mounted. Mounting now: "
    sudo mount $MOBILE_MP
    if [ $? != 0 ]; then exit; fi
fi

mv $MOBILE_MP/dcim/Camera/* "/home/joe/_Defy/__Incomming"
#rsync -r $MOBILE_MP/DCIM/100MSDCF/ /home/joe/_Handy/_Incomming --del --progress
