#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Opens a VNC Session to my Server or starts JDownloader if started on the server

if [ `hostname` = "miranda" ]
then
  java -jar /home/joe/.jd/JDownloader.jar
else
  vncviewer -passwd /home/joe/.vnc/miranda miranda
fi