#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Opens a VNC Session to my Server or starts JDownloader if started on the server

if [ `hostname` = "miranda" ]
then
  java -jar /usr/local/JD/JDownloader.jar
else
  vncviewer -passwd /home/joe/.vnc/michelle michelle:0
fi
