#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Opens a VNC Session to my Server or starts JDownloader if started on the server

if [ `hostname` = "mae" ]
then
  java -jar /usr/local/JD/JDownloader.jar -branch NIGHTLY
else
  vncviewer -passwd /home/joe/.vnc/miranda miranda
fi
