#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Mounts my Mobile and copys the File to the given location.

if [ $# -lt 1 ]; then
  echo "Use: $0 <File to send to mobile> [Location on Mobile]"
  echo "Possible Locations are: "
  echo -e "Filme \nMusik \nBilder \nXXX \nMythTV \nHörbücher \nOther \n Filme is the default"
  exit
fi

FILE_IN=$1
TO_IN=$2
MOBILE_MP="/mnt/c905/Memory_Stick"

if [[ "$FILE_IN" =~ ^/ ]];
  then
    FROM=$FILE_IN
  else
    FROM=`pwd`/$FILE_IN
fi

[ "$TO_IN" = "" ] && read -t 30 -p "Wohin soll kopiert werden?
Filme 
Musik 
Bilder 
XXX 
Other 
TV | MythTV
Hörbücher
Filme ist Standard
" TO_IN; echo 

case $TO_IN in
"Filme"*)
  TO=$MOBILE_MP"/Video/_Handyvideos";;
"Musik"*)
  TO=$MOBILE_MP"/Music";;
"Bilder"*)
  TO=$MOBILE_MP"/Picture";;
"XXX"*)
  TO=$MOBILE_MP"/Video/podcast/Eigene";;
"TV"*)
  TO=$MOBILE_MP"/Music/podcast/MythTV";;
"MythTV"*)
  TO=$MOBILE_MP"/Music/podcast/MythTV";;
"Hörbücher"*)
  TO=$MOBILE_MP"/Music/Hörbücher";;
"Other"*)
  TO=$MOBILE_MP"/Other";;
*)
  TO=$MOBILE_MP"/Video";;
esac

mount | grep $MOBILE_MP ; # <-- z.B. /home
if [ $? == 0 ] ;
  then	    # Aktion wenn bereits gemountet;
    echo "Already mounted - Good!"
  else      # Aktion wenn noch nicht gemountet;
    echo "Not mounted. Mounting now: "
    sudo mount $MOBILE_MP
    echo "Status of mount: $?"
fi

if [ -d $TO ]
  then  
    echo "Good! $TO already there!"
  else
    echo "Creating $TO"
    mkdir $TO
fi 

echo -e "rsync '$FROM' \t$TO."
rsync --progress -r "$FROM" "$TO"

