#!/bin/bash
 
###########
#
# Suggested execution format in the job settings for the backend (in general of the backend setup)
# Remember to allow the job to run in the backend general settings too :)
#
# autoaudio.sh %FILE% %STARTTIMEISO% "%TITLE%"
#
###########

if [ $# -lt 1 ]; then
  echo "Use: $0 <File> <Starttime ISO> <Title>"
  echo -e "Converts a MythTV Radio recording to a Mp3 file and calls movetomobile"
  exit
fi

BASEDIR="/home/mythtv/Video/"
OUTPUTDIR="$BASEDIR/Radio"
INPUTDIR="$BASEDIR"
INFILE=$1
ISODATE=`date +%F`
PROGTITLE=$3
STARTDATE=${2:0:10}
 
# Split
###########
OUTFILE="$OUTPUTDIR/$STARTDATE_$PROGTITLE.mp3"
 
#transcode mp2 audio to mp3
ffmpeg -i "$INPUTDIR/$INFILE" -acodec libmp3lame -ab 192k -ar 44100 -f mp3 "$OUTFILE"
 
# Tag
##########
YEAR=`date +%Y`
id3tag --artist="$PROGTITLE" --song="$PROGTITLE - $STARTDATE" --comment="" -y$YEAR -A"Radio" "$OUTFILE"

movetomobile "$OUTFILE" "TV"
if [ $? == 0 ]; then mv "$OUTFILE" "$OUTFILE_sucess"; echo "Successfully moved $OUTFILE to Mobile"; fi
