#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Mounts a TC Volume with private Data.

MOUNTPOINT="/home/_Multimedia/.Privat"
mount | grep $MOUNTPOINT ; # <-- z.B. /home
if [ $? == 0 ] ;
  then	    # Aktion wenn bereits gemountet;
    echo "Already mounted - Good!"
  else      # Aktion wenn noch nicht gemountet;
    echo "Not mounted. Mounting now: "
	xterm -title 'mount private'  -e 'tc_mount private'
    echo "Status of mount: $?"
	if [ $? == 0 ] ;
	  then      # Erfolgreich
		echo "Erfolgreich"
	  else      # Anderes!
		echo "Exit status: $?"
		return $?
	fi
fi

xhost "+localhost"
export SUDO_ASKPASS="/usr/bin/ask_pass"
sudo -A -u quota picasa
#sudo "truecrypt -t -d $MOUNTPOINT"