#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Prepends a 4-Digit random number before any file in the current directory
# A little randomizer for Old Car Radios with a real bad built in Random funciton

for F in *
do
  RNUMBER=$((RANDOM%899+100))
  NEW_FILE_NAME=$RNUMBER"_"$F
  $(mv "$F" "$NEW_FILE_NAME")
done
