#!/usr/bin/python
import sys,os,time,socket
import xmpp
from datetime import datetime

pid = str(os.getpid())+'\n'
open('/home/.shark.pid','w').write(pid)


port = 60123
port_out = 60124

if len(sys.argv)==2:
  port = int(sys.argv[1])

  
print "Port: %s" % str(port)

listener=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
listener.bind(('',port))
listener.listen(5)

sender=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sender.bind(('',port_out))
sender.listen(5)


today=datetime.today()

def Test():
  while 1:
    conn,addr = listener.accept()
    text = 'Verbindung beendet!\nIP: %(a)s \nUhrzeit: %(t)s' % {'a': addr, 't': datetime.today() }
    Send("Johannes.Dielmann@googlemail.com", text)
    print "___________"
    print text
    print "___________________Verbindung beendet____________________"
    #data = listener.recv(1024)
    #print 'Received', repr(data)
    break


while 1:
  print ("Ready. Waiting for Connections: ")
  print ("Datum: %s" % str(today))
  conn,addr = listener.accept()
  #conn_out,addr = sender.accept()
  text = 'Server Online!\nIP: %(a)s \nUhrzeit: %(t)s' % {'a': addr, 't': datetime.today() }
  print(text)
  print conn.recv()

  #os.system("kdialog --title \"Server Online\" --sorry \"%s\"" % text)
  #Send("shizodem@jabber.org", text)
  #Send("Johannes.Dielmann@googlemail.com", text)
  #Test()

