#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Updates the portage tree and all overlays.
# emerges all updates
# emerges some ebuilds with a SVN version number
# calls revdep-rebuild and some other updaters
# Writes evrything to a log and sends it via email

LOG="/var/log/portage/auto_merge_uD.log"
MAILADDR="sysgroup"
DATE=`date +%Y-%m-%d_%Hh%Mm`
PID="/var/run/start-merge.pid"
if [[ -e $PID ]]; 
then
  echo "PID vorhanden! Starte nicht!" > $LOG
  exit
fi
touch $PID
if [[ $1 ==  "--sync" ]]; 
then
  echo -e "________________________SYNC PORTAGE TREE_______________________\n" >  $LOG
  #emerge --sync 						 	       >> $LOG
  eix-sync -q #								       >> $LOG
  #echo -e "___________________________BUILD LIST__________________________\n" >> $LOG
#else
  #echo -e "___________________________BUILD LIST___________________________\n" > $LOG
fi
#emerge world -uDpv >> $LOG
echo -e "________________________BUILDING PACKAGES_________________________\n" >> $LOG
emerge system -uDNq --keep-going --jobs=2				  2>&1 >> $LOG
echo -e "_______"\n							       >> $LOG
emerge world  -uDNq --keep-going --jobs=2				  2>&1 >> $LOG
#echo -e "____________________________EIX MERGE____________________________\n" >> $LOG
#PACKAGES=`eix '-u*' --format '<installedversions:NAMESLOT>'`
#echo $PACKAGES 							       >> $LOG
#emerge --keep-going $PACKAGES
#echo -e "___________________________MEINE BUILDS___________________________\n" >> $LOG
#emerge media-video/ffmpeg 	-q					       >> $LOG
#echo -e "_______"\n							       >> $LOG
#emerge www-client/chromium 	-q 					  2>&1 >> $LOG
#emerge www-client/chromium-bin -qu 					       >> $LOG
#echo -e "___________________________TEMP BUILDS___________________________\n" >> $LOG
#perl-cleaner --all 							       >> $LOG
#python-updater 							       >> $LOG
echo -e "__________________________REVDEP REBUILD__________________________\n" >> $LOG
revdep-rebuild -- --keep-going -q 					       >> $LOG
echo -e "________________________________END_______________________________\n" >> $LOG
cat "$LOG" | mail -s "Automerge vom $DATE:" "Johannes.Dielmann@gmail.com"
#cat "$LOG" | xsend.py "Johannes.Dielmann@googlemail.com" 
xsend.py "Johannes.Dielmann@googlemail.com/androidb620c96cd02a" "Automerge fertiggestellt um `date +%Y-%m-%d_%Hh%Mm`"

rm $PID
