#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Updates the portage tree and all overlays.
# emerges all updates
# emerges some ebuilds with a SVN version number
# calls revdep-rebuild and some other updaters
# Writes evrything to a log and sends it via email

LOG="/var/log/portage/auto_merge_uD.log"
MAILADDR="sysgroup"
DATE=`date +%Y-%m-%d_%Hh%Mm`
PID="/var/run/start-merge.pid"
if [[ -e $PID ]]; 
then
  echo "PID vorhanden! Starte nicht!" > $LOG
  exit
fi
touch $PID
if [[ $1 ==  "--sync" ]]; 
then
  echo -e "________________________SYNC PORTAGE TREE________________________\n" >  $LOG
  #emerge --sync >> $LOG
  eix-sync >> $LOG
  echo -e "___________________________BUILD LIST____________________________\n" >> $LOG
else
  echo -e "___________________________BUILD LIST____________________________\n" > $LOG
fi
emerge world -uDpv >> $LOG
echo -e "________________________BUILDING PACKAGES________________________\n" >> $LOG
emerge system -uDNq --keep-going --jobs=2 >> $LOG
echo -e "_______"\n							   >> $LOG
emerge world  -uDNq --keep-going --jobs=2 >> $LOG
echo -e "____________________________EIX MERGE____________________________\n" >> $LOG
PACKAGES=`eix '-u*' --format '<installedversions:NAMESLOT>'`
echo $PACKAGES >> $LOG
emerge --keep-going $PACKAGES
echo -e "___________________________MEINE BUILDS__________________________\n" >> $LOG
emerge media-video/ffmpeg 	-q	>> $LOG
echo -e "_______"\n							   >> $LOG
emerge www-client/chromium 	-q 	>> $LOG
#emerge www-client/chromium-bin -qu 	>> $LOG
#echo -e "________________________PRESERVED REBUILD________________________\n" >> $LOG
#emerge @preserved-rebuild --keep-going -q >> $LOG
#echo -e "___________________________TEMP BUILDS___________________________\n" >> $LOG
#perl-cleaner --all >> $LOG
#python-updater >> $LOG
echo -e "__________________________REVDEP REBUILD__________________________\n" >> $LOG
revdep-rebuild -- --keep-going -q >> $LOG
echo -e "________________________________END_______________________________\n" >> $LOG
cat "$LOG" | mail -s "Automerge vom $DATE:" "Johannes.Dielmann@gmail.com"
cat "$LOG" | xsend.py "Johannes.Dielmann@gmail.com" 

rm $PID
