#!/bin/bash
#
# A bash script by JoeD - Joe84D@gmail.com
#
# Kills the listening program to free the port and opens the real Client Application
# restart listener after closing the client.

cat /home/.shark.pid | xargs kill
VirtualBox --comment WinXP\(shark\) --startvm ede5c38f-20b0-42ee-832b-89df8e6f90bb
shark_online &